services:
  connection.factory.phongo:
    class: Vainyl\Mongo\Factory\PhongoConnectionFactory
  database.factory.phongo:
    class: Vainyl\Mongo\Factory\PhongoDatabaseFactory
    arguments: ['@connection.storage']